"""add organization_id to vehicle

Revision ID: 86af2a936d97
Revises: 64bf4a936c97
Create Date: 2025-04-25 14:13:05.813289

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '86af2a936d97'
down_revision: Union[str, None] = '64bf4a936c97'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vehicles', sa.Column('organization_id', postgresql.UUID(as_uuid=True), nullable=True))
    op.create_foreign_key('fk_vehicles_organization_id', 'vehicles', 'organizations', ['organization_id'], ['id'])
    
    # Make it not nullable after existing rows are updated
    op.execute("UPDATE vehicles SET organization_id = (SELECT id FROM organizations LIMIT 1)")
    op.alter_column('vehicles', 'organization_id', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_vehicles_organization_id', 'vehicles', type_='foreignkey')
    op.drop_column('vehicles', 'organization_id')
    # ### end Alembic commands ### 