"""Add Sold To fields

Revision ID: 9a4af8cfa8b2
Revises: befb297ed97b
Create Date: 2025-05-10 00:52:21.058223

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9a4af8cfa8b2'
down_revision: Union[str, None] = 'befb297ed97b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vehicles', sa.Column('sold_to_id', sa.UUID(), nullable=True))
    op.add_column('vehicles', sa.Column('sold_at', sa.DateTime(timezone=True), nullable=True))
    op.create_foreign_key(None, 'vehicles', 'customers', ['sold_to_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'vehicles', type_='foreignkey')
    op.drop_column('vehicles', 'sold_at')
    op.drop_column('vehicles', 'sold_to_id')
    # ### end Alembic commands ###
