"""Add Vehicle Fields

Revision ID: b82a8289e70a
Revises: 86af2a936d97
Create Date: 2025-04-27 16:35:22.683672

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b82a8289e70a'
down_revision: Union[str, None] = '86af2a936d97'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vehicles', sa.Column('model_year', sa.Integer(), nullable=False))
    op.add_column('vehicles', sa.Column('fuel_type', sa.String(), nullable=False))
    op.add_column('vehicles', sa.Column('color', sa.String(), nullable=True))
    op.add_column('vehicles', sa.Column('description', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vehicles', 'description')
    op.drop_column('vehicles', 'color')
    op.drop_column('vehicles', 'fuel_type')
    op.drop_column('vehicles', 'model_year')
    # ### end Alembic commands ###
