"""Add Organization Metadata

Revision ID: fbd1348aa183
Revises: 41d2a527134a
Create Date: 2025-02-21 11:28:52.983721

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fbd1348aa183'
down_revision: Union[str, None] = '41d2a527134a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organizations', sa.Column('created_by_id', sa.UUID(), nullable=True))
    op.add_column('organizations', sa.Column('updated_by_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'organizations', 'users', ['created_by_id'], ['id'])
    op.create_foreign_key(None, 'organizations', 'users', ['updated_by_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'organizations', type_='foreignkey')
    op.drop_constraint(None, 'organizations', type_='foreignkey')
    op.drop_column('organizations', 'updated_by_id')
    op.drop_column('organizations', 'created_by_id')
    # ### end Alembic commands ###
